Fixes Issue #1 Added Resist Physical and Resist Poison Potion.
Terasology/Alchemy pull request #6
Opened 2019-03-14 10:59 UTC by majordwarf

Added 2 new potion prefabs. Didn't included the speed potion prefab as it already existed under name "RecipeWalkSpeedPotion".

2019-03-16 22:56 UTC, jellysnake commented
You seem to have something mixed up with the code? The recipe for the *ResistPhysicalPotion* and actually contains the speed potion recipe. And the recipe for *ResistPoisonPotion* is actually for the resist physical potion

2019-03-17 13:45 UTC, majordwarf commented
I see, some of the changes made in IntelliJ were not saved and I committed using GitKraken so I forgot to cross check.

2019-03-22 04:16 UTC, Cervator commented
I can try to check on this a bit more but two questions first @majordwarf :-)

* Could you check on your Git config locally on whatever system you worked on for this? Your commits aren't connecting to your GitHub user. Usually that's from not having an associated email in both Git and GitHub.
* Have you been able to test these recipes in-game? Do they work? Could you supply easy copy-paste-able commands needed to fetch the crafting station and ingredients? That'd make it super easy to test 👍

2019-03-22 07:30 UTC, e-aakash commented on assets/prefabs/recipe/brew/RecipeResistPhysicalPotion.prefab
> +}
It is good practice to add newline at end of file.
same for other file added

2019-03-29 00:27 UTC, syntaxi requested changes

2019-03-29 00:27 UTC, syntaxi commented on assets/prefabs/recipe/brew/RecipeResistPhysicalPotion.prefab
> +            "Alchemy:HealingHerb": 2,
You've got an extra comma here.
That'll cause it to spit out errors

2019-03-29 00:27 UTC, syntaxi commented on assets/prefabs/recipe/brew/RecipeResistPoisonPotion.prefab
> +            "Alchemy:PoisonHerb": 2,
Again, extra comma

2019-04-13 04:51 UTC, merged